export type TimeZone = 
  // 亚洲时区
  | 'Asia/Shanghai'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Asia/Hong_Kong'
  | 'Asia/Singapore'
  | 'Asia/Taipei'
  | 'Asia/Bangkok'
  | 'Asia/Dubai'
  | 'Asia/Kolkata'
  // 欧洲时区
  | 'Europe/London'
  | 'Europe/Paris'
  | 'Europe/Berlin'
  | 'Europe/Moscow'
  | 'Europe/Rome'
  // 美洲时区
  | 'America/New_York'
  | 'America/Los_Angeles'
  | 'America/Chicago'
  | 'America/Toronto'
  | 'America/Sao_Paulo'
  | 'America/Mexico_City'
  // 大洋洲时区
  | 'Australia/Sydney'
  | 'Australia/Melbourne'
  | 'Pacific/Auckland'
  // 非洲时区
  | 'Africa/Johannesburg'
  | 'Africa/Cairo';
